runtime: python27
api_version: 1
threadsafe: false

handlers:
  - url: /console/static
    static_dir: console/app/view/static

  - url: /console.*
    script: console/app/console.py

    # (The rest of your handlers go below this line)
  - url: /stylesheets
    static_dir: stylesheets

  - url: /purge
    script: display_kml.py

    # login: admin
  - url: /.*
    script: display_kml.main

libraries:
  - name: jinja2
    version: latest
